benchmark_configs: {
  id: "cramfs-module-not-available"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:12.0" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }
    title: "Ensure cramfs kernel module is not available"
    description:
      "The cramfs filesystem type is a compressed read-only Linux filesystem embedded in"
      "small footprint systems. A cramfs image can be used without having to first"
      "decompress the image."
    rationale:
      "Removing support for unneeded filesystem types reduces the local attack surface of the"
      "system. If this filesystem type is not needed, disable it."
    remediation:
      "Run the following script to unload and disable the cramfs module:"
      "- IF - the cramfs kernel module is available in ANY installed kernel:"		
      "• Create a file ending in .conf with install cramfs /bin/false in the"
      "/etc/modprobe.d/ directory"
      "• Create a file ending in .conf with blacklist cramfs in the /etc/modprobe.d/"
      "directory"
      "• Run modprobe -r cramfs 2>/dev/null; rmmod cramfs 2>/dev/null to"
      "remove cramfs from the kernel"
      "- IF - the cramfs kernel module is not available on the system, or pre-compiled into the"
      "kernel, no remediation is necessary"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "scan_type_specific:{instance_scanning:{"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/lib/modules/\""
      "        filename_regex: \"cramfs.ko\""
      "        recursive: true"
      "      }}"
      "      existence:{should_exist: false}"
      "    }"      
      "  }"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"install cramfs .*\""
      "          expected_regex: \"install cramfs /bin/(true|false)\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"blacklist cramfs.*\""
      "          expected_regex: \"blacklist cramfs.*\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{single_file:{path:\"/proc/modules\"}}"
      "      content_entry:{"
      "        match_type: NONE_MATCH"
      "        match_criteria: {"
      "          filter_regex: \"cramfs .*\""
      "          expected_regex: \"cramfs .*\""
      "        }"
      "      }"
      "    }"
      "  }"
      "}"
      "image_scanning:{"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/lib/modules/\""
      "        filename_regex: \"cramfs.ko\""
      "        recursive: true"
      "      }}"
      "      existence:{should_exist: false}"
      "    }"      
      "  }"	  
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"install cramfs .*\""
      "          expected_regex: \"install cramfs /bin/(true|false)\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"blacklist cramfs.*\""
      "          expected_regex: \"blacklist cramfs.*\""
      "        }"
      "      }"
      "    }"
      "  }"
      "}}"
  }
}

benchmark_configs: {
  id: "freevxfs-module-not-available"
  compliance_note: {
    version: { cpe_uri: "cpe:/o:debian:debian_linux:12.0" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }
    title: "Ensure freevxfs kernel module is not available"
    description:
      "The freevxfs filesystem type is a free version of the Veritas type filesystem. This is the"
      "primary filesystem type for HP-UX operating systems."
    rationale:
      "Removing support for unneeded filesystem types reduces the local attack surface of the"
      "system. If this filesystem type is not needed, disable it."
    remediation:
      "Run the following script to unload and disable the freevxfs module:"
      "- IF - the freevxfs kernel module is available in ANY installed kernel:"
      "• Create a file ending in .conf with install freevxfs /bin/false in the"
      "/etc/modprobe.d/ directory"
      "• Create a file ending in .conf with blacklist freevxfs in the"
      "/etc/modprobe.d/ directory"
      "• Run modprobe -r freevxfs 2>/dev/null; rmmod freevxfs 2>/dev/null"
      "to remove freevxfs from the kernel"
      "- IF - the freevxfs kernel module is not available on the system, or pre-compiled into"
      "the kernel, no remediation is necessary"
    cis_benchmark: {
      profile_level: 1
      severity: LOW
    }
    scan_instructions:
      "scan_type_specific:{instance_scanning:{"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/lib/modules/\""
      "        filename_regex: \"freevxfs.ko\""
      "        recursive: true"
      "      }}"
      "      existence:{should_exist: false}"
      "    }"      
      "  }"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"install freevxfs .*\""
      "          expected_regex: \"install freevxfs /bin/(true|false)\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"blacklist freevxfs.*\""
      "          expected_regex: \"blacklist freevxfs.*\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{single_file:{path:\"/proc/modules\"}}"
      "      content_entry:{"
      "        match_type: NONE_MATCH"
      "        match_criteria: {"
      "          filter_regex: \"freevxfs .*\""
      "          expected_regex: \"freevxfs .*\""
      "        }"
      "      }"
      "    }"
      "  }"
      "}"
      "image_scanning:{"
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/lib/modules/\""
      "        filename_regex: \"freevxfs.ko\""
      "        recursive: true"
      "      }}"
      "      existence:{should_exist: false}"
      "    }"      
      "  }"	  
      "  check_alternatives:{"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"install freevxfs .*\""
      "          expected_regex: \"install freevxfs /bin/(true|false)\""
      "        }"
      "      }"
      "    }"
      "    file_checks:{"
      "      files_to_check:{files_in_dir:{"
      "        dir_path:\"/etc/modprobe.d\""
      "        filename_regex: \".*\\\\.conf\""
      "        recursive: true"
      "      }}"
      "      content_entry:{"
      "        match_type: ALL_MATCH_ANY_ORDER"
      "        match_criteria: {"
      "          filter_regex: \"blacklist freevxfs.*\""
      "          expected_regex: \"blacklist freevxfs.*\""
      "        }"
      "      }"
      "    }"
      "  }"
      "}}"
  }
}

