version: { cpe_uri: "cpe:/o:debian:debian_linux:12.0" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }

benchmark_id: "cramfs-module-not-available"
benchmark_id: "freevxfs-module-not-available"
benchmark_id: "hfs-module-not-available"
benchmark_id: "hfsplus-module-not-available"
benchmark_id: "jffs2-module-not-available"
benchmark_id: "overlayfs-module-not-available"
benchmark_id: "squashfs-module-not-available"
benchmark_id: "udf-module-not-available"
benchmark_id: "usb_storage-module-not-available"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "shm-configured"
benchmark_id: "shm-nodev"
benchmark_id: "shm-nosuid"
benchmark_id: "shm-noexec"
benchmark_id: "separate-partition-home"
benchmark_id: "home-nodev"
benchmark_id: "home-nosuid"
