
version: { cpe_uri: "cpe:/o:debian:debian_linux:12.0" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }

benchmark_id: "cramfs-module-not-available"
benchmark_id: "freevxfs-module-not-available"
benchmark_id: "hfs-module-not-available"
benchmark_id: "hfsplus-module-not-available"
benchmark_id: "jffs2-module-not-available"
benchmark_id: "overlayfs-module-not-available"
benchmark_id: "squashfs-module-not-available"
benchmark_id: "udf-module-not-available"
benchmark_id: "usb_storage-module-not-available"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "shm-configured"
benchmark_id: "shm-nodev"
benchmark_id: "shm-nosuid"
benchmark_id: "shm-noexec"
benchmark_id: "separate-partition-home"
benchmark_id: "home-nodev"
benchmark_id: "home-nosuid"
benchmark_id: "separate-partition-var"
benchmark_id: "var-nodev"
benchmark_id: "var-nosuid"
benchmark_id: "separate-partition-var-tmp"
benchmark_id: "var-tmp-nodev"
benchmark_id: "var-tmp-nosuid"
benchmark_id: "var-tmp-noexec"
benchmark_id: "separate-partition-var-log"
benchmark_id: "var-log-nodev"
benchmark_id: "var-log-nosuid"
benchmark_id: "var-log-noexec"
benchmark_id: "separate-partition-var-log-audit"
benchmark_id: "var-log-audit-nodev"
benchmark_id: "var-log-audit-nosuid"
benchmark_id: "var-log-audit-noexec"
benchmark_id: "ensure-apparmor-installed"
benchmark_id: "apparmor-enabled-bootloader"
benchmark_id: "bootloader-password-set"
benchmark_id: "aslr-enabled"
benchmark_id: "ptrace-scope-restricted"
benchmark_id: "core-dumps-restricted"
benchmark_id: "motd-configured"
benchmark_id: "etc-issue-configured"
benchmark_id: "etc-issue-net-configured"
benchmark_id: "motd-access"
benchmark_id: "etc-issue-access"
benchmark_id: "etc-issue-net-access"
benchmark_id: "ensure-gdm-removed"
benchmark_id: "autofs-service-disabled"
benchmark_id: "avahi-daemon-service-disabled"
benchmark_id: "dhcp-server-service-disabled"
benchmark_id: "dns-server-service-disabled"
benchmark_id: "dnsmasq-service-disabled"
benchmark_id: "ftp-server-service-disabled"
benchmark_id: "ldap-server-service-disabled"
benchmark_id: "message-access-server-service-disabled"
benchmark_id: "network-fs-service-disabled"
benchmark_id: "nis-service-disabled"
benchmark_id: "cups-service-disabled"
benchmark_id: "rpcbind-service-disabled"
benchmark_id: "rsync-service-disabled"
benchmark_id: "smb-file-server-service-disabled"
benchmark_id: "snmp-service-disabled"
benchmark_id: "tftp-server-service-disabled"
benchmark_id: "squid-service-disabled"
benchmark_id: "web-server-service-disabled"
benchmark_id: "xinetd-service-disabled"
benchmark_id: "x-server-service-disabled"
benchmark_id: "mail-transfer-agent-is-configured-for-localonly-mode"
benchmark_id: "nis-client-not-installed"
benchmark_id: "rsh-client-not-installed"
benchmark_id: "talk-client-not-installed"
benchmark_id: "telnet-client-not-installed"
benchmark_id: "ldap-client-not-installed"
benchmark_id: "ensure-ftp-client-not-installed"
benchmark_id: "ensure-single-time-sync-daemon"
benchmark_id: "systemd-timesyncd-configured"
benchmark_id: "chrony-configured"
benchmark_id: "ensure-chrony-running-as-user-chrony"
benchmark_id: "cron-daemon-enabled"
benchmark_id: "crontab-permissions"
benchmark_id: "cron-hourly-permissions"
benchmark_id: "cron-daily-permissions"
benchmark_id: "cron-weekly-permissions"
benchmark_id: "cron-monthly-permissions"
benchmark_id: "cron-d-permissions"