version: { cpe_uri: "cpe:/o:debian:debian_linux:12.0" version: "1.1.0" benchmark_document: "CIS Debian Linux 12" }

benchmark_id: "cramfs-module-not-available"
benchmark_id: "freevxfs-module-not-available"
benchmark_id: "hfs-module-not-available"
benchmark_id: "hfsplus-module-not-available"
benchmark_id: "jffs2-module-not-available"
benchmark_id: "overlayfs-module-not-available"
