version: { cpe_uri: "cpe:/o:debian:ubuntu_linux:22.04" version: "1.0.0" benchmark_document: "CIS Ubuntu 22.04" }
benchmark_id: "cramfs-mounting-disabled"
benchmark_id: "squashfs-mounting-disabled"
benchmark_id: "udf-mounting-disabled"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "shm-nodev"
benchmark_id: "shm-nosuid"
benchmark_id: "shm-noexec"
benchmark_id: "var-tmp-nodev"
benchmark_id: "var-tmp-nosuid"
benchmark_id: "var-tmp-noexec"
benchmark_id: "apparmor-installed"
benchmark_id: "bootloader-password-set"
benchmark_id: "bootloader-config-permissions"
benchmark_id: "aslr-enabled"
benchmark_id: "core-dumps-restricted"
benchmark_id: "motd-configured"
benchmark_id: "local-login-warning-configured"
benchmark_id: "gdm-login-banner-configured"
benchmark_id: "xdcmp-not-enabled"
benchmark_id: "dhcp-server-disabled"
benchmark_id: "ftp-server-disabled"
benchmark_id: "ldap-server-disabled"
benchmark_id: "nfs-rpc-disabled"
benchmark_id: "nis-server-disabled"
benchmark_id: "rsync-disabled"
benchmark_id: "samba-disabled"
benchmark_id: "snmp-server-disabled"


