version: { cpe_uri: "cpe:/o:debian:ubuntu_linux:22.04" version: "1.0.0" benchmark_document: "CIS Ubuntu 22.04" }
benchmark_id: "cramfs-mounting-disabled"
benchmark_id: "squashfs-mounting-disabled"
benchmark_id: "udf-mounting-disabled"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "shm-nodev"
benchmark_id: "shm-nosuid"
benchmark_id: "shm-noexec"
benchmark_id: "var-tmp-nodev"
benchmark_id: "var-tmp-nosuid"
benchmark_id: "var-tmp-noexec"
benchmark_id: "apparmor-installed"
benchmark_id: "bootloader-password-set"
benchmark_id: "bootloader-config-permissions"
benchmark_id: "aslr-enabled"
benchmark_id: "core-dumps-restricted"
benchmark_id: "motd-configured"
benchmark_id: "local-login-warning-configured"
benchmark_id: "gdm-login-banner-configured"
benchmark_id: "xdcmp-not-enabled"
benchmark_id: "dhcp-server-disabled"
benchmark_id: "ftp-server-disabled"
benchmark_id: "ldap-server-disabled"
benchmark_id: "nfs-rpc-disabled"
benchmark_id: "nis-server-disabled"
benchmark_id: "rsync-disabled"
benchmark_id: "samba-disabled"
benchmark_id: "snmp-server-disabled"
benchmark_id: "mail-transfer-agent-is-configured-for-localonly-mode"
benchmark_id: "rsh-client-not-installed"
benchmark_id: "talk-client-not-installed"
benchmark_id: "telnet-client-not-installed"
benchmark_id: "ldap-client-not-installed"
benchmark_id: "chrony-configured"
benchmark_id: "cron-daemon-enabled"
benchmark_id: "crontab-permissions"
benchmark_id: "cron-hourly-permissions"
benchmark_id: "cron-daily-permissions"
benchmark_id: "cron-weekly-permissions"
benchmark_id: "cron-monthly-permissions"
benchmark_id: "cron-d-permissions"
benchmark_id: "at-cron-restricted-to-authorized-users"
benchmark_id: "ip-forwarding-disabled"
benchmark_id: "packet-redirect-sending-disabled"
benchmark_id: "bogus-icmp-responses-ignored"
benchmark_id: "broadcast-icmp-requests-ignored"