version: { cpe_uri: "cpe:/o:debian:ubuntu_linux:22.04" version: "1.0.0" benchmark_document: "CIS Ubuntu 22.04" }
benchmark_id: "cramfs-mounting-disabled"
benchmark_id: "squashfs-mounting-disabled"
benchmark_id: "hfsplus-mounting-disabled"
benchmark_id: "jffs2-mounting-disabled"
benchmark_id: "udf-mounting-disabled"
benchmark_id: "usb-storage-disabled"
benchmark_id: "tmp-configured"
benchmark_id: "tmp-nodev"
benchmark_id: "tmp-nosuid"
benchmark_id: "tmp-noexec"
benchmark_id: "separate-partition-shm"
benchmark_id: "shm-nodev"
benchmark_id: "shm-noexec"
benchmark_id: "apparmor-installed"
benchmark_id: "bootloader-password-set"
benchmark_id: "bootloader-config-permissions"
benchmark_id: "aslr-enabled"
benchmark_id: "core-dumps-restricted"
benchmark_id: "motd-configured"
benchmark_id: "gdm-login-banner-configured"
benchmark_id: "xdcmp-not-enabled"
benchmark_id: "dhcp-server-disabled"
benchmark_id: "ftp-server-disabled"
benchmark_id: "ldap-server-disabled"
benchmark_id: "nfs-rpc-disabled"
benchmark_id: "nis-server-disabled"
benchmark_id: "rsync-disabled"
benchmark_id: "samba-disabled"
benchmark_id: "snmp-server-disabled"
benchmark_id: "rsh-client-not-installed"
benchmark_id: "talk-client-not-installed"
benchmark_id: "telnet-client-not-installed"
benchmark_id: "ldap-client-not-installed"
benchmark_id: "chrony-configured"
benchmark_id: "cron-daemon-enabled"
benchmark_id: "crontab-permissions"
benchmark_id: "cron-hourly-permissions"
benchmark_id: "cron-daily-permissions"
benchmark_id: "cron-weekly-permissions"
benchmark_id: "cron-monthly-permissions"
benchmark_id: "cron-d-permissions"
benchmark_id: "at-cron-restricted-to-authorized-users"
benchmark_id: "ip-forwarding-disabled"
benchmark_id: "packet-redirect-sending-disabled"
benchmark_id: "bogus-icmp-responses-ignored"
benchmark_id: "broadcast-icmp-requests-ignored"
benchmark_id: "icmp-redirects-not-accepted"
benchmark_id: "secure-icmp-redirects-not-accepted"
benchmark_id: "reverse-path-filtering-enabled"
benchmark_id: "source-routed-packets-not-accepted"
benchmark_id: "suspicious-packets-logged"
benchmark_id: "tcp-syn-cookies-enabled"
benchmark_id: "ipv6-router-advertisements-not-accepted"
benchmark_id: "sshd-config-permissions"
benchmark_id: "sshd-private-host-key-permissions"
benchmark_id: "sshd-public-host-key-permissions"
benchmark_id: "ssh-idle-timeout-interval-configured"
benchmark_id: "ssh-maxauthtries-4-or-less"
benchmark_id: "sudo-commands-use-pty"
benchmark_id: "sudo-log-file-exists"
benchmark_id: "access-to-su-restricted"
benchmark_id: "password-expiration-365-days-or-less"
benchmark_id: "password-expiration-warning-days-7-or-more"
benchmark_id: "last-password-change-date-in-past"
benchmark_id: "root-is-only-uid-0-account"
benchmark_id: "root-path-integrity"
benchmark_id: "default-user-shell-timeout-900-or-less"
benchmark_id: "aide-installed"
benchmark_id: "filesystem-integrity-checked"
benchmark_id: "etc-passwd-permissions"
benchmark_id: "etc-group-permissions"
benchmark_id: "etc-group-dash-permissions"
benchmark_id: "etc-shadow-permissions"
benchmark_id: "etc-shadow-dash-permissions"
benchmark_id: "etc-gshadow-permissions"
benchmark_id: "etc-gshadow-dash-permissions"
benchmark_id: "groups-from-etc-passwd-in-etc-group"
benchmark_id: "shadow-group-empty"
benchmark_id: "no-duplicate-uids"
benchmark_id: "no-duplicate-gids"
benchmark_id: "no-duplicate-user-names"
benchmark_id: "no-duplicate-group-names"
benchmark_id: "var-nodev"
benchmark_id: "prelink-disabled"
benchmark_id: "avahi-disabled"
benchmark_id: "dns-server-disabled"
benchmark_id: "x-not-installed"
benchmark_id: "nis-client-not-installed"
benchmark_id: "sshd-banner-configured"
benchmark_id: "sshd-access-configured"
benchmark_id: "sshd-disable-forwarding-configured"
benchmark_id: "sshd-gssapi-authentication-disabled"
benchmark_id: "sshd-hostbasedauthentication-disabled"
benchmark_id: "ssh-ignorerhosts-enabled"
benchmark_id: "strong-key-exchange-algos-used"
benchmark_id: "ssh-logingrace-one-minute-or-less"
benchmark_id: "ssh-loglevel-appropriate"